services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
    ports:
      - 5432:5432
    volumes:
      - ./data/:/var/lib/postgresql/data
